# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include:
#  - galerie
  - _pages
  # - archiv

url: http://raffael.one
# url: http://raffaelj.github.io
base: "/raffael.one"
imgpath: /img
galpath: /galerie

# empty arrays
emptyArray: []

# externes Dateien-Lager
edata: http://data.raffael.one

sass: # :expanded or :compressed
  style: :compressed

paginate: 10
paginate_path: "/blog/page:num/"

# Permalink-Struktur für Blog-Posts
permalink: /blog/:year/:month/:day/:title

# Titel für RSS-Feed
title: www.raffael.one
# Untertitel
subtitle: Kunst - Bildung - Design
# description - wenn nicht in Seite definiert
description: "Ich performe mit Hoopdance und Poledance auf Ihrer Party oder gebe Kunst- und Hula-Hoop-Workshops auf Ihrem Festival. Oder suchen Sie eine Feuershow für Ihr Event? Nebenbei gebe ich auch Grafik- und Webdesign-Kurse."

collections:
  gallery:
    output: true
    permalink: /galerie/:path/
  kursangebote:
    output: false
    permalink: /kurse/:path/
  referenzen_grafik_webdesign:
    output: false
    permalink: /referenzen_grafik_webdesign/:path/
  pressemappe:
    output: false
    permalink: /pressemappe/:path/
  # projekte:
    # output: true
    # permalink: /projekte/:path/

defaults:
- scope:
    path: ""
  values:
    layout: "default"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    license: "cc-by-nc-sa"
    author: "Raffael Jesche"
- scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
- scope:
    path: ""
    type: "kursangebote"
  values:
    layout: "default"
- scope:
    path: ""
    type: "referenzen_grafik_webdesign"
  values:
    layout: "default"
- scope:
    path: ""
    type: "pressemappe"
  values:
    layout: "default"
