# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include:
#  - galerie
  - _pages
  - archiv

url: http://raffael.one
# url: http://raffaelj.github.io
base: "/raffael.one"
imgpath: /images
galpath: /gallery

# empty arrays
emptyArray: []

# externes Dateien-Lager
edata: http://data.raffael.one

sass: # :expanded or :compressed
  style: :compressed

paginate: 9
paginate_path: "/blog/page:num/"

# Permalink-Struktur für Blog-Posts
permalink: /blog/:year/:month/:day/:title

collections:
  gallery:
    output: true
    permalink: /gallery/:path/
  kursangebote:
    output: true
    permalink: /kurse/:path/
  referenzen_grafik_webdesign:
    output: true
    permalink: /referenzen_grafik_webdesign/:path/
  pressemappe:
    output: true
    permalink: /pressemappe/:path/

defaults:
- scope:
    path: ""
  values:
    layout: "default"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
    # license: "cc-by-nc-sa"
    # author: "Raffael"
- scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
- scope:
    path: ""
    type: "kursangebote"
  values:
    layout: "default"
- scope:
    path: ""
    type: "referenzen_grafik_webdesign"
  values:
    layout: "default"
- scope:
    path: ""
    type: "pressemappe"
  values:
    layout: "default"
